# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 

    The version of the OpenAPI document: 60.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ssl_api import SSLApi


class TestSSLApi(unittest.TestCase):
    """SSLApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SSLApi()

    def tearDown(self) -> None:
        pass

    def test_generate_sslcsr(self) -> None:
        """Test case for generate_sslcsr

        Generate SSL CSR
        """
        pass

    def test_get_ssl_status(self) -> None:
        """Test case for get_ssl_status

        Get SSL status
        """
        pass

    def test_install_ssl_certificate(self) -> None:
        """Test case for install_ssl_certificate

        Install SSL certificate
        """
        pass

    def test_provision_ssl_certificates(self) -> None:
        """Test case for provision_ssl_certificates

        Provision SSL certificates
        """
        pass


if __name__ == '__main__':
    unittest.main()
