# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 

    The version of the OpenAPI document: 60.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dns_api import DNSApi


class TestDNSApi(unittest.TestCase):
    """DNSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DNSApi()

    def tearDown(self) -> None:
        pass

    def test_add_dns_custom_a_record(self) -> None:
        """Test case for add_dns_custom_a_record

        Add DNS custom A record
        """
        pass

    def test_add_dns_custom_record(self) -> None:
        """Test case for add_dns_custom_record

        Add DNS custom record
        """
        pass

    def test_add_dns_secondary_nameserver(self) -> None:
        """Test case for add_dns_secondary_nameserver

        Add DNS secondary nameserver
        """
        pass

    def test_get_dns_custom_a_records_for_q_name(self) -> None:
        """Test case for get_dns_custom_a_records_for_q_name

        Get DNS custom A records
        """
        pass

    def test_get_dns_custom_records(self) -> None:
        """Test case for get_dns_custom_records

        Get DNS custom records
        """
        pass

    def test_get_dns_custom_records_for_q_name_and_type(self) -> None:
        """Test case for get_dns_custom_records_for_q_name_and_type

        Get DNS custom records
        """
        pass

    def test_get_dns_dump(self) -> None:
        """Test case for get_dns_dump

        Get DNS dump
        """
        pass

    def test_get_dns_secondary_nameserver(self) -> None:
        """Test case for get_dns_secondary_nameserver

        Get DNS secondary nameserver
        """
        pass

    def test_get_dns_zonefile(self) -> None:
        """Test case for get_dns_zonefile

        Get DNS zonefile
        """
        pass

    def test_get_dns_zones(self) -> None:
        """Test case for get_dns_zones

        Get DNS zones
        """
        pass

    def test_remove_dns_custom_a_record(self) -> None:
        """Test case for remove_dns_custom_a_record

        Remove DNS custom A record
        """
        pass

    def test_remove_dns_custom_record(self) -> None:
        """Test case for remove_dns_custom_record

        Remove DNS custom record
        """
        pass

    def test_update_dns(self) -> None:
        """Test case for update_dns

        Update DNS
        """
        pass

    def test_update_dns_custom_a_record(self) -> None:
        """Test case for update_dns_custom_a_record

        Update DNS custom A record
        """
        pass

    def test_update_dns_custom_record(self) -> None:
        """Test case for update_dns_custom_record

        Update DNS custom record
        """
        pass


if __name__ == '__main__':
    unittest.main()
