# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 

    The version of the OpenAPI document: 60.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemApi()

    def tearDown(self) -> None:
        pass

    def test_get_relay_config(self) -> None:
        """Test case for get_relay_config

        Get SMTP relay configuration
        """
        pass

    def test_get_system_backup_config(self) -> None:
        """Test case for get_system_backup_config

        Get system backup config
        """
        pass

    def test_get_system_backup_status(self) -> None:
        """Test case for get_system_backup_status

        Get system backup status
        """
        pass

    def test_get_system_privacy_status(self) -> None:
        """Test case for get_system_privacy_status

        Get system privacy status
        """
        pass

    def test_get_system_reboot_status(self) -> None:
        """Test case for get_system_reboot_status

        Get system reboot status
        """
        pass

    def test_get_system_status(self) -> None:
        """Test case for get_system_status

        Get system status
        """
        pass

    def test_get_system_updates(self) -> None:
        """Test case for get_system_updates

        Get system updates
        """
        pass

    def test_get_system_upstream_version(self) -> None:
        """Test case for get_system_upstream_version

        Get system upstream version
        """
        pass

    def test_get_system_version(self) -> None:
        """Test case for get_system_version

        Get system version
        """
        pass

    def test_perform_system_backup(self) -> None:
        """Test case for perform_system_backup

        Perform system backup
        """
        pass

    def test_reboot_system(self) -> None:
        """Test case for reboot_system

        Reboot system
        """
        pass

    def test_set_relay_config(self) -> None:
        """Test case for set_relay_config

        Set SMTP relay configuration
        """
        pass

    def test_update_system_backup_config(self) -> None:
        """Test case for update_system_backup_config

        Update system backup config
        """
        pass

    def test_update_system_packages(self) -> None:
        """Test case for update_system_packages

        Update system packages
        """
        pass

    def test_update_system_privacy(self) -> None:
        """Test case for update_system_privacy

        Update system privacy
        """
        pass


if __name__ == '__main__':
    unittest.main()
