# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 

    The version of the OpenAPI document: 60.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.mail_api import MailApi


class TestMailApi(unittest.TestCase):
    """MailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailApi()

    def tearDown(self) -> None:
        pass

    def test_add_mail_user(self) -> None:
        """Test case for add_mail_user

        Add mail user
        """
        pass

    def test_add_mail_user_privilege(self) -> None:
        """Test case for add_mail_user_privilege

        Add mail user privilege
        """
        pass

    def test_get_mail_aliases(self) -> None:
        """Test case for get_mail_aliases

        Get mail aliases
        """
        pass

    def test_get_mail_domains(self) -> None:
        """Test case for get_mail_domains

        Get mail domains
        """
        pass

    def test_get_mail_user_privileges(self) -> None:
        """Test case for get_mail_user_privileges

        Get mail user privileges
        """
        pass

    def test_get_mail_users(self) -> None:
        """Test case for get_mail_users

        Get mail users
        """
        pass

    def test_remove_mail_alias(self) -> None:
        """Test case for remove_mail_alias

        Remove mail alias
        """
        pass

    def test_remove_mail_user(self) -> None:
        """Test case for remove_mail_user

        Remove mail user
        """
        pass

    def test_remove_mail_user_privilege(self) -> None:
        """Test case for remove_mail_user_privilege

        Remove mail user privilege
        """
        pass

    def test_set_mail_user_password(self) -> None:
        """Test case for set_mail_user_password

        Set mail user password
        """
        pass

    def test_upsert_mail_alias(self) -> None:
        """Test case for upsert_mail_alias

        Upsert mail alias
        """
        pass


if __name__ == '__main__':
    unittest.main()
