# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 

    The version of the OpenAPI document: 60.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.pgp_api import PGPApi


class TestPGPApi(unittest.TestCase):
    """PGPApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PGPApi()

    def tearDown(self) -> None:
        pass

    def test_export_pgp_key(self) -> None:
        """Test case for export_pgp_key

        Export a PGP key
        """
        pass

    def test_get_pgp_key(self) -> None:
        """Test case for get_pgp_key

        Get a specific PGP key
        """
        pass

    def test_get_pgp_keys(self) -> None:
        """Test case for get_pgp_keys

        Get all PGP keys
        """
        pass

    def test_import_pgp_key(self) -> None:
        """Test case for import_pgp_key

        Import a PGP key
        """
        pass

    def test_remove_pgp_key(self) -> None:
        """Test case for remove_pgp_key

        Remove a PGP key
        """
        pass


if __name__ == '__main__':
    unittest.main()
