/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MailUserPrivilege } from '../models/MailUserPrivilege';
import { MeAuthStatus } from '../models/MeAuthStatus';
import { HttpFile } from '../http/http';

/**
* Me (user) response.
*/
export class MeResponse {
    'apiKey'?: string;
    /**
    * Email format.
    */
    'email'?: string;
    'privileges'?: Array<MailUserPrivilege>;
    'reason'?: string;
    'status': MeAuthStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKey",
            "baseName": "api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "privileges",
            "baseName": "privileges",
            "type": "Array<MailUserPrivilege>",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MeAuthStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



