/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PgpKeySubkeysInner {
    'algorithm': string;
    'auth': boolean;
    'cert': boolean;
    'encr': boolean;
    'sign': boolean;
    'bits': number;
    'expired': boolean;
    'expires': number;
    'expiresDays': Date;
    'fpr': string;
    'master': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth",
            "baseName": "auth",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cert",
            "baseName": "cert",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "encr",
            "baseName": "encr",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sign",
            "baseName": "sign",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bits",
            "baseName": "bits",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "expiresDays",
            "baseName": "expires_days",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fpr",
            "baseName": "fpr",
            "type": "string",
            "format": ""
        },
        {
            "name": "master",
            "baseName": "master",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PgpKeySubkeysInner.attributeTypeMap;
    }

    public constructor() {
    }
}

