/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The result of the key import operation
*/
export class PgpKeyImportResult {
    /**
    * Keys in the import
    */
    'keysRead': number;
    /**
    * New keys
    */
    'keysAdded': number;
    /**
    * Keys that were not modified
    */
    'keysUnchanged': number;
    /**
    * New user ID\'s
    */
    'uidsAdded': number;
    /**
    * New key signatures
    */
    'sigsAdded': number;
    /**
    * New revocation certificates
    */
    'revsAdded': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keysRead",
            "baseName": "keys_read",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "keysAdded",
            "baseName": "keys_added",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "keysUnchanged",
            "baseName": "keys_unchanged",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "uidsAdded",
            "baseName": "uids_added",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sigsAdded",
            "baseName": "sigs_added",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "revsAdded",
            "baseName": "revs_added",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PgpKeyImportResult.attributeTypeMap;
    }

    public constructor() {
    }
}

