/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PgpKeySubkeysInner } from '../models/PgpKeySubkeysInner';
import { HttpFile } from '../http/http';

/**
* Parseable, human-friendly information about a PGP key
*/
export class PgpKey {
    'ids': Array<string>;
    'idsEmails'?: Array<string>;
    'masterFpr': string;
    'revoked': boolean;
    'subkeys': Array<PgpKeySubkeysInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "idsEmails",
            "baseName": "ids_emails",
            "type": "Array<string>",
            "format": "email"
        },
        {
            "name": "masterFpr",
            "baseName": "master_fpr",
            "type": "string",
            "format": ""
        },
        {
            "name": "revoked",
            "baseName": "revoked",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subkeys",
            "baseName": "subkeys",
            "type": "Array<PgpKeySubkeysInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PgpKey.attributeTypeMap;
    }

    public constructor() {
    }
}

