/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SystemBackupStatus } from '../models/SystemBackupStatus';
import { HttpFile } from '../http/http';

/**
* Backup status response. Lists the status for all backups.
*/
export class SystemBackupStatusResponse {
    'backups'?: Array<SystemBackupStatus>;
    'unmatchedFileSize': number;
    'error'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "backups",
            "baseName": "backups",
            "type": "Array<SystemBackupStatus>",
            "format": ""
        },
        {
            "name": "unmatchedFileSize",
            "baseName": "unmatched_file_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemBackupStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

