/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * OpenAPI spec version: 60.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebDomainSslCertificateInner } from '../models/WebDomainSslCertificateInner';
import { HttpFile } from '../http/http';

/**
* Web domain details.
*/
export class WebDomain {
    'customRoot': string;
    /**
    * Hostname format.
    */
    'domain': string;
    'root': string;
    'sslCertificate': Set<WebDomainSslCertificateInner>;
    'staticEnabled': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customRoot",
            "baseName": "custom_root",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": "hostname"
        },
        {
            "name": "root",
            "baseName": "root",
            "type": "string",
            "format": ""
        },
        {
            "name": "sslCertificate",
            "baseName": "ssl_certificate",
            "type": "Set<WebDomainSslCertificateInner>",
            "format": ""
        },
        {
            "name": "staticEnabled",
            "baseName": "static_enabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebDomain.attributeTypeMap;
    }

    public constructor() {
    }
}

